"""Generation stage for the Unofficial Guide RAG system.

Retrieves the most relevant chunks for a question (via embed.retrieve), formats
them into a numbered, source-labeled context block, and asks the Groq-hosted
llama-3.3-70b-versatile model to answer using ONLY that context. Source
attribution is extracted programmatically from the retrieval results — the model
is never trusted to report its own sources.

Run directly to test grounding (including an out-of-scope refusal):

    python generate.py

Requires GROQ_API_KEY in a .env file (see .env.example).
"""

import os

from dotenv import load_dotenv
from groq import Groq

from embed import retrieve

# Load GROQ_API_KEY (and anything else) from .env into the environment.
load_dotenv()

MODEL_NAME = "llama-3.3-70b-versatile"
TOP_K = 5

# The exact refusal string the model is instructed to emit when the context is
# insufficient. Kept as a constant so callers/tests can compare against it.
REFUSAL = "I don't have enough information in my documents to answer that."

SYSTEM_PROMPT = (
    "You are a helpful assistant that answers questions about UT Austin "
    "CS professors and courses. "
    "Use ONLY the information in the context provided below to answer. "
    "Do not use outside knowledge. "
    "If the answer cannot be found in the context, say: "
    "'I don't have enough information in my documents to answer that.' "
    "Always cite which source documents you used in your answer."
)

# Create the Groq client once at import time. Raises if the key is missing,
# which surfaces a misconfigured .env immediately rather than at first query.
_client = Groq(api_key=os.environ["GROQ_API_KEY"])


def _format_context(chunks: list[dict]) -> str:
    """Render retrieved chunks as a numbered list, each labeled with its source."""
    blocks = []
    for i, chunk in enumerate(chunks, start=1):
        blocks.append(f"[{i}] (source: {chunk['source']})\n{chunk['text']}")
    return "\n\n".join(blocks)


def ask(question: str) -> dict:
    """Answer `question` strictly from retrieved context.

    Returns a dict with:
      - "answer":  the model's response text
      - "sources": deduplicated source filenames from the retrieved chunks,
                   extracted programmatically (not generated by the model)
    """
    chunks = retrieve(question, k=TOP_K)

    # Deduplicate sources while preserving retrieval (closest-first) order.
    sources = list(dict.fromkeys(chunk["source"] for chunk in chunks))

    context = _format_context(chunks)
    user_message = (
        f"Context:\n{context}\n\n"
        f"Question: {question}"
    )

    response = _client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0,
    )
    answer = response.choices[0].message.content.strip()

    return {"answer": answer, "sources": sources}


if __name__ == "__main__":
    test_questions = [
        "What do students say about Mike Scott's exams in CS314?",
        "Should I take Chatterjee or Joshi for CS429?",
        "What is the food like at UT Austin?",  # out-of-scope refusal test
    ]

    for question in test_questions:
        result = ask(question)
        print("=" * 70)
        print(f"Q: {question}")
        print("-" * 70)
        print(f"A: {result['answer']}")
        print(f"Sources: {result['sources']}")
        print("=" * 70)
        print()
